### ISSUE TITLE
Traceback when filtering hosts with network_element_facts

### ISSUE THREAD

**Issue by 49phil** [Forcepoint/fp-NGFW-SMC-ansible#7]
Hello,

some general information first:
* SMC Version: 7.1.3 [11429]
* latest commit of this repository (https://github.com/Forcepoint/fp-NGFW-SMC-ansible/commit/70c2bef0b354386f85242af79bb2b07d01f16eac)
* fp-NGFW-SMC-python 1.0.25
* ansible [core 2.16.10]
* python version 3.11.2

We are experiencing issues when trying to filter for specific host elements by using the network_element_facts module. Our task looks like this:
```
- name: Get current host elements
  network_element_facts:
    element: "host"
    filter: 172.16.14.13
```

And this is the traceback we receive:
```
Traceback (most recent call last):
  File "REDACTED/AnsiballZ_network_element_facts.py", line 107, in <module>
    _ansiballz_main()
  File "REDACTED/AnsiballZ_network_element_facts.py", line 99, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "REDACTED/AnsiballZ_network_element_facts.py", line 47, in invoke_module
    runpy.run_module(mod_name='ansible.modules.ansible.legacy.network_element_facts', init_globals=dict(_module_fqn='ansible.modules.ansible.legacy.network_element_facts', _modlib_path=modlib_path),
  File "<frozen runpy>", line 226, in run_module
  File "<frozen runpy>", line 98, in _run_module_code
  File "<frozen runpy>", line 88, in _run_code
  File "/tmp/ansible_ansible.legacy.network_element_facts_payload_2neeraur/ansible_ansible.legacy.network_element_facts_payload.zip/ansible/modules/ansible/legacy/network_element_facts.py", line 191, in <module>
  File "/tmp/ansible_ansible.legacy.network_element_facts_payload_2neeraur/ansible_ansible.legacy.network_element_facts_payload.zip/ansible/modules/ansible/legacy/network_element_facts.py", line 188, in main
  File "/tmp/ansible_ansible.legacy.network_element_facts_payload_2neeraur/ansible_ansible.legacy.network_element_facts_payload.zip/ansible/modules/ansible/legacy/network_element_facts.py", line 161, in __init__
  File "/tmp/ansible_ansible.legacy.network_element_facts_payload_2neeraur/ansible_ansible.legacy.network_element_facts_payload.zip/ansible/module_utils/smc_util.py", line 516, in __init__
  File "/tmp/ansible_ansible.legacy.network_element_facts_payload_2neeraur/ansible_ansible.legacy.network_element_facts_payload.zip/ansible/module_utils/smc_util.py", line 685, in success
  File "/tmp/ansible_ansible.legacy.network_element_facts_payload_2neeraur/ansible_ansible.legacy.network_element_facts_payload.zip/ansible/module_utils/basic.py", line 1511, in exit_json
  File "/tmp/ansible_ansible.legacy.network_element_facts_payload_2neeraur/ansible_ansible.legacy.network_element_facts_payload.zip/ansible/module_utils/basic.py", line 1500, in _return_formatted
  File "/tmp/ansible_ansible.legacy.network_element_facts_payload_2neeraur/ansible_ansible.legacy.network_element_facts_payload.zip/ansible/module_utils/common/parameters.py", line 927, in remove_values
  File "/tmp/ansible_ansible.legacy.network_element_facts_payload_2neeraur/ansible_ansible.legacy.network_element_facts_payload.zip/ansible/module_utils/common/parameters.py", line 453, in _remove_values_conditions
TypeError: ThirdPartyMonitoring.__init__() missing 1 required positional argument: 'data'
```

So the error seems to be with the ThirdPartyMonitoring class in the smc-python library when ansible tries to create an empty object of it.

These issues only pop up when trying to filter for a host and the task is actually returning elements. So if the filter would not return a value, like with this example against the demo SMC installation, then the task does not run into an error:
```
- name: Get current host elements
  ansible.legacy.network_element_facts:
    element: "host"
    filter: 250.240.250.240
```
The ansible run shows (with -vvv argument):
```
ok: [localhost] => {
    "ansible_facts": {
        "elements": []
    },
    "changed": false,
    "invocation": {
        "module_args": {
            "as_yaml": false,
            "case_sensitive": true,
            "element": "host",
            "exact_match": false,
            "expand": [],
            "filter": "250.240.250.240",
            "limit": 0,
            "smc_address": "REDACTED",
            "smc_alt_filepath": null,
            "smc_api_key": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "smc_api_version": null,
            "smc_domain": null,
            "smc_extra_args": {
                "verify": false
            },
            "smc_logging": null,
            "smc_timeout": 30
        }
    }
}
```
Also not filtering at all and simply requesting all or a limited amount of host elements works fine too.

We have also tested this on both an instance of the demo SMC with its default data and our production SMC and both exhibit the same issue.

Thank you very much in advance.

**Comment by amol-suruse** [comment]
Hello,

We have created an internal issue to fix it. it will be fixed in the next release.
Thanks
